// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtO9YJ7AcT_N2f9FVsq_8ItqaxA71IXRk',
    appId: '1:210075791729:web:3eb2dc89857631cecf46d0',
    messagingSenderId: '210075791729',
    projectId: 'ahra-partner',
    authDomain: 'ahra-partner.firebaseapp.com',
    storageBucket: 'ahra-partner.firebasestorage.app',
    measurementId: 'G-P7WZMS35E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaTtTEOOqXeM1lqvD_3rGUvME4jvC7JyU',
    appId: '1:210075791729:android:c1bbaa35f0c780dfcf46d0',
    messagingSenderId: '210075791729',
    projectId: 'ahra-partner',
    storageBucket: 'ahra-partner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSg7JamrfiV2df1OGfpBJlIguISRPvpGU',
    appId: '1:210075791729:ios:452d712f72336329cf46d0',
    messagingSenderId: '210075791729',
    projectId: 'ahra-partner',
    storageBucket: 'ahra-partner.firebasestorage.app',
    iosBundleId: 'com.example.aharaPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSg7JamrfiV2df1OGfpBJlIguISRPvpGU',
    appId: '1:210075791729:ios:452d712f72336329cf46d0',
    messagingSenderId: '210075791729',
    projectId: 'ahra-partner',
    storageBucket: 'ahra-partner.firebasestorage.app',
    iosBundleId: 'com.example.aharaPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtO9YJ7AcT_N2f9FVsq_8ItqaxA71IXRk',
    appId: '1:210075791729:web:0f457551d3a31dc7cf46d0',
    messagingSenderId: '210075791729',
    projectId: 'ahra-partner',
    authDomain: 'ahra-partner.firebaseapp.com',
    storageBucket: 'ahra-partner.firebasestorage.app',
    measurementId: 'G-1271H2KH5N',
  );
}
